<body></body>
<script>

  const PENDING = 'PENDING',
        FULFILLED = 'FULFILLED',
        REJECTED = 'REJECTD'

function resolovePromise(promise2, x, resolve, reject) {
  if (promise2 === x) {
    return reject(new TypeError('promise and x can not refer to the same object'))
  }
  let hasCall = false;
  if ((typeof x ==="object" && typeof x !== null) || typeof x === "function") {
    try {
      let then = x.then
      
      if (typeof then === "function") {
        then.call(x, (y) => {
          if (hasCall) return;
          hasCall = true
          resolovePromise(promise2, y, resolve, reject)
        }, (r) => {
          if (hasCall) return;
          hasCall = true            
          reject(r)
        })
      } else {
        resolve(x);
      }
    } catch (e) {
      if (hasCall) return;
      hasCall = true      
      reject(e)
    }
  } else {
    resolve(x);
  }
  
}

  class MyPromise {
    constructor (executor) {
      this.status = PENDING;
      this.value = undefined;
      this.reason = undefined;

      this.onFulfilledCallbacks = [];
      this.onRejectedCallbacks = [];

      const resolve = (value) => {
        if (this.status === PENDING) {
          this.status = FULFILLED;
          this.value = value
        }

        this.onFulfilledCallbacks.forEach(fn => fn())
      }

      const reject = (reason) => {
        if (this.status === PENDING) {
          this.status = REJECTED;
          this.reason = reason;
        }

        this.onRejectedCallbacks.forEach(fn => fn())
      }
      try {
        executor(resolve, reject);
      } catch (error) {
        reject(error)
      }
    }

    then (onFulfilled, onRejected) {
      onFulfilled = typeof onFulfilled === "function" ? onFulfilled : (value) => value;
      onRejected = typeof onRejected === "function" ? onRejected : (reason) => { throw reason };

      let promise2 = new MyPromise((resolve, reject) => {
        if (this.status === FULFILLED) {
          setTimeout(() => {
            try {
              const x = onFulfilled(this.value)
              resolovePromise(promise2, x, resolve, reject)
            } catch (error) {
              reject(error)
            }
          }, 0)
        }
        if (this.status === REJECTED) {
          setTimeout(() => {
            try {
              const x = onRejected(this.reason)
              resolovePromise(promise2, x, resolve, reject)
            } catch (error) {
              reject(error)
            }
          }, 0)
        }
        if (this.status === PENDING) {
          // 订阅过程
          this.onFulfilledCallbacks.push(() => {
            try {
              const x = onFulfilled(this.value)
              resolovePromise(promise2, x, resolve, reject)
            } catch (error) {
              reject(error)
            }
          })
          this.onRejectedCallbacks.push(() => {
            try {
              const x = onRejected(this.reason)
              resolovePromise(promise2, x, resolve, reject)
            } catch (error) {
              reject(error)
            }
          })
        }
      })

      return promise2
    }

    catch(errorCallback) {
      return this.then(null, errorCallback);
    }
  }

  let promise = new MyPromise((resolve, reject) => {
    // resolve('success1')
    // reject('Error')
    // throw new Error('Exception: Error')
    setTimeout(() => {
      resolve('success')
    }, 2000)
  })

  promise.then((value) => {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve(new MyPromise((resolve, reject) => {
          resolve('tttttttt')
        }))
      }, 500)
    })
  }, (reason) => {
    console.log(reason);
  })
  .then((value) => {
    console.log(value)
  })
</script>